switching to typescript
michael-leonov/find-pair pull request #6
Opened 2022-08-10 07:45 UTC by michael-leonov

2022-08-10 20:09 UTC, yadimko commented on src/js/game-logic.ts
> +    dataset: { rang: any };
старайся не использовать any

2022-08-10 20:17 UTC, yadimko requested changes

2022-08-10 20:17 UTC, yadimko commented on src/js/game-logic.ts
> +    dataset: { rang: any };
старайся не использовать any

2022-08-10 20:17 UTC, yadimko commented on src/js/game-logic.ts
> +    removeEventListener: (arg0: string, arg1: (this: any) => void) => void;
any

2022-08-10 20:17 UTC, yadimko commented on src/js/game-logic.ts
> +    dataset: { rang: any };
типы можешь вынести в отдельный файл в папке - types.ts например

2022-08-10 20:17 UTC, yadimko commented on src/js/game-logic.ts
> +function flipCard(this: any): void {
any

2022-08-10 20:17 UTC, yadimko commented on src/js/game-logic.ts
> +  const cards: NodeListOf<Element> = document.querySelectorAll('.card-wrapper');
https://www.typescriptlang.org/docs/handbook/dom-manipulation.html

2022-08-10 20:17 UTC, yadimko commented on src/js/game-logic.ts
> +    const cards: NodeListOf<Element> =
https://www.typescriptlang.org/docs/handbook/dom-manipulation.html
если будут трудности в понимании - пиши

2022-08-10 20:17 UTC, yadimko commented on src/js/game-logic.ts
> +      (el as HTMLElement).style.pointerEvents = 'none';
гуд)

2022-08-10 20:17 UTC, yadimko commented on src/js/generate-cards.ts
> +export const countCards: 3 = 3;
это что за 3?)

2022-08-10 20:17 UTC, yadimko commented on src/js/generate-cards.ts
> +      fieldCards!.appendChild(cardWrapper);
тут я не в курсе - зачем тут '!' ?

2022-08-10 20:17 UTC, yadimko commented on src/js/http-request.ts
> +  onError: (data: any) => void;
any

2022-08-10 20:17 UTC, yadimko commented on src/main.ts
> +    statusComplexity?: any;
any и можно вынести из функции в отдельный файл

2022-08-10 20:17 UTC, yadimko commented on src/main.ts
> +        addEventListener: (arg0: string, arg1: () => void) => any;
any

2022-08-10 20:17 UTC, yadimko commented on src/main.ts
> +          contains: (arg0: string) => any;
тоже

2022-08-10 20:17 UTC, yadimko commented on src/main.ts
> +        dataset: { complexity: any };
и тут

2022-08-10 20:18 UTC, yadimko commented
Оставил комменты. Пиши в слаку в чат если будет что то непонятно

2022-08-11 07:06 UTC, michael-leonov commented on src/js/generate-cards.ts
> +      fieldCards!.appendChild(cardWrapper);
точно даем понять, что fieldCards не null

2022-08-11 07:57 UTC, michael-leonov commented on src/js/game-logic.ts
> +    removeEventListener: (arg0: string, arg1: (this: any) => void) => void;
исправил

2022-08-11 07:57 UTC, michael-leonov commented on src/js/game-logic.ts
> +  removeEventListener: (arg0: string, arg1: (this: any) => void) => void;
вот тут this: any не понимаю

2022-08-11 07:57 UTC, michael-leonov commented on src/main.ts
> +        addEventListener: (arg0: string, arg1: () => void) => any;
() => void) => any тут не понимаю

2022-08-11 07:57 UTC, michael-leonov commented on src/js/game-logic.ts
> +  const cards: NodeListOf<Element> = document.querySelectorAll('.card-wrapper');
не понял, в смысле для queryselectorall нужно указывать?
![image](https://user-images.githubusercontent.com/109069404/184088732-e40edc3e-5c90-412c-b53f-08e05a65ea2c.png)

2022-08-11 07:57 UTC, michael-leonov commented on src/js/game-logic.ts
> +    removeEventListener: (arg0: string, arg1: (this: any) => void) => void;
arg1: (this: any) непонятно

2022-08-11 21:44 UTC, yadimko approved these changes

2022-08-11 21:44 UTC, yadimko commented on src/js/game-logic.ts
> +  removeEventListener: (arg0: string, arg1: (this: any) => void) => void;
https://stackoverflow.com/questions/28920753/declaring-the-type-of-this-in-a-typescript-function

2022-08-11 21:44 UTC, yadimko commented on src/js/game-logic.ts
> +  const cards: NodeListOf<Element> = document.querySelectorAll('.card-wrapper');
document.querySelectorAll<HTMLDivElement>('.card-wrapper') попробуй пожалуйста так

2022-08-19 07:16 UTC, michael-leonov commented
@mrerberg heeeelp

2022-08-22 09:39 UTC, merged

2022-08-24 08:12 UTC, mrerberg commented on src/js/game-logic.ts
> +      arg0: string,
arg0 почему так назван аргумент? Почему название не описывает суть аргумента?

2022-08-24 08:12 UTC, mrerberg commented on src/js/game-logic.ts
> +  resetBoard();
Почему функция по дизейблу карт еще знает что-то о ресете борды? Это не ее зона ответственности

2022-08-24 08:12 UTC, mrerberg commented on src/js/game-logic.ts
> +  (imgStatus as HTMLImageElement).src = imgUrl;
лучше

const imgStatus: HTMLImageElement | null

Чем использование as

2022-08-24 08:12 UTC, mrerberg commented on src/js/game-logic.ts
> +  [hasFlippedCard, lockBoard] = [false, false];
Зачем нужна такая конструкция?

2022-08-24 08:12 UTC, mrerberg commented on src/main.ts
> +  (function chooseComplexity(types: any[]): void {
any?

2022-08-24 08:12 UTC, mrerberg commented on src/main.ts
> +            ((complexity: Del): void => {
Зачем такая мутерная конструкция?
 
 Просто delete complexity.status; не сделать?

2022-08-24 08:43 UTC, michael-leonov commented on src/main.ts
> +            ((complexity: Del): void => {
![image](https://user-images.githubusercontent.com/109069404/186372326-c63e05b3-d95a-42a3-ace5-3785a11c3d05.png)
![image](https://user-images.githubusercontent.com/109069404/186372379-b3c3b886-9594-44df-a6c0-df83650d4583.png)
Вот такая ошибка, почитал
https://coderoad.ru/63702057/%D0%92-%D1%87%D0%B5%D0%BC-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D0%B0-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8-TypeScript-%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80-delete-%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD-%D0%B1%D1%8B%D1%82%D1%8C-%D0%BD%D0%B5%D0%BE%D0%B1%D1%8F%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%BC

2022-08-24 09:00 UTC, michael-leonov commented on src/js/game-logic.ts
> +  resetBoard();
ну после того как карты задезейблили, делаем резет карт и доски

2022-08-24 09:03 UTC, michael-leonov commented on src/js/game-logic.ts
> +  (imgStatus as HTMLImageElement).src = imgUrl;
падает с ошибкой(что-то типа объект может быть null), если строго не задаем, что это htmlelement

2022-08-24 09:09 UTC, michael-leonov commented on src/js/game-logic.ts
> +      arg0: string,
ну это помощь от ts) не подумал про название аргументов, а должно быть что-то типа 
`let firstCard: {
    dataset: { rang: string };
    removeEventListener: (
      `**click**`: string,`
??

2022-08-24 09:12 UTC, michael-leonov commented on src/js/game-logic.ts
> +  [hasFlippedCard, lockBoard] = [false, false];
сброс состояния флипнутой карты и доски

2022-08-24 09:18 UTC, michael-leonov commented on src/main.ts
> +  (function chooseComplexity(types: any[]): void {
вот тут я не знаю, писал в первом же сообщение уроке по TypeScript
![image](https://user-images.githubusercontent.com/109069404/186380591-dc8554e5-c120-454c-8b7f-4dfa4be9d3c8.png)